name: Release php-8.1-dev-node-14 image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1' # Every monday 08:00

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Convert IMAGE_NAME tp lowercase
        run: |
          echo "IMAGE_NAME_LOWERCASE=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image - PHP 8.1 dev
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./php-8.1-dev-node
          build-args: |
            NODE_VERSION=14.15.4
            YARN_VERSION=1.22.5
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWERCASE }}:8.1-dev-node-14
